swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /avocado:
    get:
      operationId: avocado.read_all
      tags:
        - avocado
      summary: Read the entire set of avocado, sorted by id
      description: Read the entire set of avocado, sorted by id
      responses:
        200:
          description: Successfully read avocado set operation
          schema:
            type: array
            items:
              properties:
                id:
                  type: string
                  description: Id of the avocado
                date:
                  type: string
                avgprice:
                  type: number
                  
                totalvol:
                  type: number
                  
                avo_a:
                  type: number
                 
                avo_b:
                  type: number
                  
                avo_c:
                  type: number
                  
                type:
                  type: number
                  
                regionid:
                  type: number
    post:
      operationId: avocado.create
      tags:
        - avocado
      summary: Create a avocado
      description: Create a new avocado
      parameters:
        - name: avocado
          in: body
          description: avocado to create
          required: True
          schema:
            type: object
            properties:
              date:
                  type: string
              avgprice:
                type: number
                
              totalvol:
                type: number
                
              avo_a:
                type: number
                
              avo_b:
                type: number
                
              avo_c:
                type: number
                
              type:
                type: number
                
              regionid:
                type: number
      responses:
        201:
          description: Successfully created avocado
          schema:
            properties:
              id:
                  type: string
                  description: Id of the avocado
              date:
                type: string
              avgprice:
                type: number
                
              totalvol:
                type: number
                
              avo_a:
                type: number
                
              avo_b:
                type: number
                
              avo_c:
                type: number
                
              type:
                type: number
                
              regionid:
                type: number


  /avocado/{id}:
    get:
      operationId: avocado.read_one
      tags:
        - avocado
      summary: Read one avocado
      description: Read one avocado
      parameters:
        - name: id
          in: path
          description: Id of the avocado to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read avocado from avocado data operation
          schema:
            type: object
            properties:
              id:
                type: string
                description: Id of the avocado
              date:
                  type: string
              avgprice:
                type: number
                
              totalvol:
                type: number
                
              avo_a:
                type: number
                
              avo_b:
                type: number
                
              avo_c:
                type: number
                
              type:
                type: number
                
              regionid:
                type: number

    put:
      operationId: avocado.update
      tags:
        - avocado
      summary: Update a avocado
      description: Update a avocado
      parameters:
        - name: id
          in: path
          description: Id the avocado to update
          type: integer
          required: True
        - name: avocado
          in: body
          schema:
            type: object
            properties:
              date:
                  type: string
              avgprice:
                type: number
                
              totalvol:
                type: number
                
              avo_a:
                type: number
                
              avo_b:
                type: number
                
              avo_c:
                type: number
                
              type:
                type: number
                
              regionid:
                type: number
      responses:
        200:
          description: Successfully updated avocado
          schema:
            properties:
              id:
                type: string
                description: Id of the avocado
              date:
                  type: string
              avgprice:
                type: number
                
              totalvol:
                type: number
                
              avo_a:
                type: number
                
              avo_b:
                type: number
                
              avo_c:
                type: number
                
              type:
                type: number
                
              regionid:
                type: number


    delete:
      operationId: avocado.delete
      tags:
        - avocado
      summary: Delete a avocado from the avocado list
      description: Delete a avocado
      parameters:
        - name: id
          in: path
          type: integer
          description: Id of the avocado to delete
          required: true
      responses:
        200:
          description: Successfully deleted a avocado

